export const LENGUAJE_SERVICE = 'LENGUAJE_SERVICE';
export const USUARIOS_SERVICE = 'USUARIOS_SERVICE';
export const RVIAAC_SERVICE = 'RVIAAC_SERVICE';
export const RVIASA_SERVICE = 'RVIASA_SERVICE';
export const RVIACO_SERVICE = 'RVIACO_SERVICE';
export const AUTH_SERVICE = 'AUTH_SERVICE';
export const NATS_SERVICE = 'NATS_SERVICE';
export const RVIACP_SERVICE = 'RVIACP_SERVICE';
